### ISSUE TITLE
Move info item

### ISSUE THREAD

**Issue by Andre601** [harry0198/MailMe#3]
The info item that explains about how to read males (send it as text) should be moved to the top of the GUI rather than being on the left hand side as this imo only confuses people and makes them think they have a mail.

**Comment by harry0198** [comment]
Which slot would you be suggesting the change be moved to? Also, the No Results icon should make it clear to the user but then again I've gotten used to looking at it.

**Comment by Andre601** [comment]
I would say in the middle of the top row (slot 5)

**Comment by harry0198** [comment]
I'll perhaps work on allowing people to define slots in the config so people can tune to their preference

**Comment by harry0198** [comment]
Basic functionality to do this has been added in the latest update
