### ISSUE TITLE
welcome mail feature doesn't work

### ISSUE THREAD

**Issue by Andre601** [harry0198/MailMe#5]
## The issue
Using `/mail admin preset welcome` does not save the mail as a welcome mail.

## Steps to reproduce
1. Run `/mail admin preset welcome`
2. Select the mail type (I selected message)
3. Select the item (I set a custom one using a book)
4. Select the recipients
5. Set your message

## What should happen
The mail should be set as welcome mail and according to the wiki should I have it in my mail box.

## What actually happens
The text you send as message is returned and the mailbox stays empty.

## Info
MailMe: 1.3.0
Server: PaperMC 155 (MC 1.15.2)

**Comment by harry0198** [comment]
Fixed in latest build 1.3.1
https://www.spigotmc.org/resources/mailme-1-13-x-1-15-x-a-better-mailing-system.76442/update?update=326738

Please note
- Welcome mail only fires when a player is new to the server (Has no PlayerData.json)
