### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by XXY233** [harry0198/MailMe#9]
**MailMe Version:** 1.4.61
**Server Version:** PaperSpigot 1.16.1

# Error when selecting icon

**Steps to reproduce:**

1. Use /mail defaultmb to create a default mailbox.
2. One person uses the default mailbox to send mail to another person.
3. Open the default mailbox again, when you select the icon, the icon will change to the mail sent by that person.
![20200818200649](https://user-images.githubusercontent.com/46647646/90511633-56241680-e18f-11ea-9666-001c6647ca0f.jpg)

# Messages repeated multiple times

**Steps to reproduce:**

1. As usual, send mail to others.
2. Click on someone multiple times on the "Choose Recipients" interface.
3. After sending, the recipient will receive many repeated prompts, and the sender will prompt "You sent some mail to [Multiple Recipients]".
![too many messages](https://user-images.githubusercontent.com/46647646/90512151-3d683080-e190-11ea-98f1-620674d978a5.gif)

**Comment by harry0198** [comment]
Hi, could you please elaborate more on the clicking on anonymous mail? The expected outcome is you click on it, it glows and you can then select your mail type. It should not send you to another menu but rather sets the option once sent to be anonymous.

**Comment by XXY233** [comment]
> Hi, could you please elaborate more on the clicking on anonymous mail? The expected outcome is you click on it, it glows and you can then select your mail type. It should not send you to another menu but rather sets the option once sent to be anonymous.
It seems that there is no problem with anonymous mail, sorry I didn't notice..😲

**Comment by XXY233** [comment]
These problems have been fixed in 1.4.62.
